spring.application.name=PartyManagement

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/PartyTentHouse?useSSL=true&requireSSL=true

spring.datasource.username=4ADEWuvQBNZQAMH.root

spring.datasource.password=lOz87aYtuudbHZ85

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=${PORT:1111}